import { TnssincronizarParametricaMotivoAnulacion } from '../definitions/TnssincronizarParametricaMotivoAnulacion';
import { TnssincronizarParametricaMotivoAnulacionResponse } from '../definitions/TnssincronizarParametricaMotivoAnulacionResponse';
import { TnssincronizarActividades } from '../definitions/TnssincronizarActividades';
import { TnssincronizarActividadesResponse } from '../definitions/TnssincronizarActividadesResponse';
import { TnssincronizarFechaHora } from '../definitions/TnssincronizarFechaHora';
import { TnssincronizarFechaHoraResponse } from '../definitions/TnssincronizarFechaHoraResponse';
import { TnssincronizarListaLeyendasFactura } from '../definitions/TnssincronizarListaLeyendasFactura';
import { TnssincronizarListaLeyendasFacturaResponse } from '../definitions/TnssincronizarListaLeyendasFacturaResponse';
import { TnssincronizarParametricaTipoHabitacion } from '../definitions/TnssincronizarParametricaTipoHabitacion';
import { TnssincronizarParametricaTipoHabitacionResponse } from '../definitions/TnssincronizarParametricaTipoHabitacionResponse';
import { TnssincronizarListaActividadesDocumentoSector } from '../definitions/TnssincronizarListaActividadesDocumentoSector';
import { TnssincronizarListaActividadesDocumentoSectorResponse } from '../definitions/TnssincronizarListaActividadesDocumentoSectorResponse';
import { TnssincronizarParametricaTipoDocumentoIdentidad } from '../definitions/TnssincronizarParametricaTipoDocumentoIdentidad';
import { TnssincronizarParametricaTipoDocumentoIdentidadResponse } from '../definitions/TnssincronizarParametricaTipoDocumentoIdentidadResponse';
import { TnssincronizarParametricaUnidadMedida } from '../definitions/TnssincronizarParametricaUnidadMedida';
import { TnssincronizarParametricaUnidadMedidaResponse } from '../definitions/TnssincronizarParametricaUnidadMedidaResponse';
import { TnssincronizarParametricaTipoDocumentoSector } from '../definitions/TnssincronizarParametricaTipoDocumentoSector';
import { TnssincronizarParametricaTipoDocumentoSectorResponse } from '../definitions/TnssincronizarParametricaTipoDocumentoSectorResponse';
import { TnssincronizarParametricaTiposFactura } from '../definitions/TnssincronizarParametricaTiposFactura';
import { TnssincronizarParametricaTiposFacturaResponse } from '../definitions/TnssincronizarParametricaTiposFacturaResponse';
import { TnsverificarComunicacion } from '../definitions/TnsverificarComunicacion';
import { TnsverificarComunicacionResponse } from '../definitions/TnsverificarComunicacionResponse';
import { TnssincronizarListaMensajesServicios } from '../definitions/TnssincronizarListaMensajesServicios';
import { TnssincronizarListaMensajesServiciosResponse } from '../definitions/TnssincronizarListaMensajesServiciosResponse';
import { TnssincronizarParametricaTipoMetodoPago } from '../definitions/TnssincronizarParametricaTipoMetodoPago';
import { TnssincronizarParametricaTipoMetodoPagoResponse } from '../definitions/TnssincronizarParametricaTipoMetodoPagoResponse';
import { TnssincronizarParametricaEventosSignificativos } from '../definitions/TnssincronizarParametricaEventosSignificativos';
import { TnssincronizarParametricaEventosSignificativosResponse } from '../definitions/TnssincronizarParametricaEventosSignificativosResponse';
import { TnssincronizarParametricaTipoPuntoVenta } from '../definitions/TnssincronizarParametricaTipoPuntoVenta';
import { TnssincronizarParametricaTipoPuntoVentaResponse } from '../definitions/TnssincronizarParametricaTipoPuntoVentaResponse';
import { TnssincronizarListaProductosServicios } from '../definitions/TnssincronizarListaProductosServicios';
import { TnssincronizarListaProductosServiciosResponse } from '../definitions/TnssincronizarListaProductosServiciosResponse';
import { TnssincronizarParametricaTipoEmision } from '../definitions/TnssincronizarParametricaTipoEmision';
import { TnssincronizarParametricaTipoEmisionResponse } from '../definitions/TnssincronizarParametricaTipoEmisionResponse';
import { TnssincronizarParametricaPaisOrigen } from '../definitions/TnssincronizarParametricaPaisOrigen';
import { TnssincronizarParametricaPaisOrigenResponse } from '../definitions/TnssincronizarParametricaPaisOrigenResponse';
import { TnssincronizarParametricaTipoMoneda } from '../definitions/TnssincronizarParametricaTipoMoneda';
import { TnssincronizarParametricaTipoMonedaResponse } from '../definitions/TnssincronizarParametricaTipoMonedaResponse';
export interface ServicioFacturacionSincronizacionPort {
    sincronizarParametricaMotivoAnulacion(sincronizarParametricaMotivoAnulacion: TnssincronizarParametricaMotivoAnulacion, callback: (err: any, result: TnssincronizarParametricaMotivoAnulacionResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    sincronizarActividades(sincronizarActividades: TnssincronizarActividades, callback: (err: any, result: TnssincronizarActividadesResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    sincronizarFechaHora(sincronizarFechaHora: TnssincronizarFechaHora, callback: (err: any, result: TnssincronizarFechaHoraResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    sincronizarListaLeyendasFactura(sincronizarListaLeyendasFactura: TnssincronizarListaLeyendasFactura, callback: (err: any, result: TnssincronizarListaLeyendasFacturaResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    sincronizarParametricaTipoHabitacion(sincronizarParametricaTipoHabitacion: TnssincronizarParametricaTipoHabitacion, callback: (err: any, result: TnssincronizarParametricaTipoHabitacionResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    sincronizarListaActividadesDocumentoSector(sincronizarListaActividadesDocumentoSector: TnssincronizarListaActividadesDocumentoSector, callback: (err: any, result: TnssincronizarListaActividadesDocumentoSectorResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    sincronizarParametricaTipoDocumentoIdentidad(sincronizarParametricaTipoDocumentoIdentidad: TnssincronizarParametricaTipoDocumentoIdentidad, callback: (err: any, result: TnssincronizarParametricaTipoDocumentoIdentidadResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    sincronizarParametricaUnidadMedida(sincronizarParametricaUnidadMedida: TnssincronizarParametricaUnidadMedida, callback: (err: any, result: TnssincronizarParametricaUnidadMedidaResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    sincronizarParametricaTipoDocumentoSector(sincronizarParametricaTipoDocumentoSector: TnssincronizarParametricaTipoDocumentoSector, callback: (err: any, result: TnssincronizarParametricaTipoDocumentoSectorResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    sincronizarParametricaTiposFactura(sincronizarParametricaTiposFactura: TnssincronizarParametricaTiposFactura, callback: (err: any, result: TnssincronizarParametricaTiposFacturaResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    verificarComunicacion(verificarComunicacion: TnsverificarComunicacion, callback: (err: any, result: TnsverificarComunicacionResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    sincronizarListaMensajesServicios(sincronizarListaMensajesServicios: TnssincronizarListaMensajesServicios, callback: (err: any, result: TnssincronizarListaMensajesServiciosResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    sincronizarParametricaTipoMetodoPago(sincronizarParametricaTipoMetodoPago: TnssincronizarParametricaTipoMetodoPago, callback: (err: any, result: TnssincronizarParametricaTipoMetodoPagoResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    sincronizarParametricaEventosSignificativos(sincronizarParametricaEventosSignificativos: TnssincronizarParametricaEventosSignificativos, callback: (err: any, result: TnssincronizarParametricaEventosSignificativosResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    sincronizarParametricaTipoPuntoVenta(sincronizarParametricaTipoPuntoVenta: TnssincronizarParametricaTipoPuntoVenta, callback: (err: any, result: TnssincronizarParametricaTipoPuntoVentaResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    sincronizarListaProductosServicios(sincronizarListaProductosServicios: TnssincronizarListaProductosServicios, callback: (err: any, result: TnssincronizarListaProductosServiciosResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    sincronizarParametricaTipoEmision(sincronizarParametricaTipoEmision: TnssincronizarParametricaTipoEmision, callback: (err: any, result: TnssincronizarParametricaTipoEmisionResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    sincronizarParametricaPaisOrigen(sincronizarParametricaPaisOrigen: TnssincronizarParametricaPaisOrigen, callback: (err: any, result: TnssincronizarParametricaPaisOrigenResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
    sincronizarParametricaTipoMoneda(sincronizarParametricaTipoMoneda: TnssincronizarParametricaTipoMoneda, callback: (err: any, result: TnssincronizarParametricaTipoMonedaResponse, rawResponse: any, soapHeader: any, rawRequest: any) => void): void;
}
