import { AppCrediantialDto } from 'src/decorators/global.decorator';
import { Client, RespuestaListaParametricas } from 'src/siap-soap/FacturacionSincronizacion';
import { RespuestaFechaHoraDTO } from './dto/RespuestaFechaHora.dto';
import { RespuestaListaActividadesDTO } from './dto/RespuestaListaActividades.dto';
import { RespuestaListaParametricasDTO } from './dto/RespuestaListaParametricas.dto';
import { RespuestaListaParametricasLeyendasDTO } from './dto/RespuestaListaParametricasLeyendas.dto';
import { RespuestaListaProductosDTO } from './dto/RespuestaListaProductos.dto';
import { ReturnDTO } from './dto/Return.dto';
import { SolicitudSincronizacionDTO } from './dto/SolicitudSincronizacion.dto';
import { Cache } from 'cache-manager';
export declare class FacturacionSincronizacionService {
    private readonly soapClient;
    private readonly soapClientTest;
    private readonly cache;
    constructor(soapClient: Client, soapClientTest: Client, cache: Cache);
    getClient(credential: AppCrediantialDto, solicitud: any): Client;
    fromCache<T>(solicitud: any, endpoint: string): Promise<T>;
    toCache(solicitud: any, endpoint: string, data: any): Promise<any>;
    clearCache(solicitud: any, endpoint: string): Promise<void>;
    resetCache(): Promise<void>;
    sincronizarParametricaMotivoAnulacion(credential: AppCrediantialDto, solicitud: SolicitudSincronizacionDTO): Promise<RespuestaListaParametricasDTO>;
    sincronizarActividades(credential: AppCrediantialDto, solicitud: SolicitudSincronizacionDTO): Promise<RespuestaListaActividadesDTO>;
    sincronizarFechaHora(credential: AppCrediantialDto, solicitud: SolicitudSincronizacionDTO): Promise<RespuestaFechaHoraDTO>;
    sincronizarListaLeyendasFactura(credential: AppCrediantialDto, solicitud: SolicitudSincronizacionDTO): Promise<RespuestaListaParametricasLeyendasDTO>;
    sincronizarParametricaTipoHabitacion(credential: AppCrediantialDto, solicitud: SolicitudSincronizacionDTO): Promise<RespuestaListaParametricasDTO>;
    sincronizarListaActividadesDocumentoSector(credential: AppCrediantialDto, solicitud: SolicitudSincronizacionDTO): Promise<RespuestaListaParametricas>;
    sincronizarParametricaTipoDocumentoIdentidad(credential: AppCrediantialDto, solicitud: SolicitudSincronizacionDTO): Promise<RespuestaListaParametricasDTO>;
    sincronizarParametricaUnidadMedida(credential: AppCrediantialDto, solicitud: SolicitudSincronizacionDTO): Promise<RespuestaListaParametricasDTO>;
    sincronizarParametricaTipoDocumentoSector(credential: AppCrediantialDto, solicitud: SolicitudSincronizacionDTO): Promise<RespuestaListaParametricasDTO>;
    sincronizarParametricaTiposFactura(credential: AppCrediantialDto, solicitud: SolicitudSincronizacionDTO): Promise<RespuestaListaParametricasDTO>;
    verificarComunicacion(credential: AppCrediantialDto, solicitud: SolicitudSincronizacionDTO): Promise<ReturnDTO>;
    sincronizarListaMensajesServicios(credential: AppCrediantialDto, solicitud: SolicitudSincronizacionDTO): Promise<RespuestaListaParametricasDTO>;
    sincronizarParametricaTipoMetodoPago(credential: AppCrediantialDto, solicitud: SolicitudSincronizacionDTO): Promise<RespuestaListaParametricasDTO>;
    sincronizarParametricaEventosSignificativos(credential: AppCrediantialDto, solicitud: SolicitudSincronizacionDTO): Promise<RespuestaListaParametricasDTO>;
    sincronizarParametricaTipoPuntoVenta(credential: AppCrediantialDto, solicitud: SolicitudSincronizacionDTO): Promise<RespuestaListaParametricasDTO>;
    sincronizarListaProductosServicios(credential: AppCrediantialDto, solicitud: SolicitudSincronizacionDTO): Promise<RespuestaListaProductosDTO>;
    sincronizarParametricaTipoEmision(credential: AppCrediantialDto, solicitud: SolicitudSincronizacionDTO): Promise<RespuestaListaParametricasDTO>;
    sincronizarParametricaPaisOrigen(credential: AppCrediantialDto, solicitud: SolicitudSincronizacionDTO): Promise<RespuestaListaParametricasDTO>;
    sincronizarParametricaTipoMoneda(credential: AppCrediantialDto, solicitud: SolicitudSincronizacionDTO): Promise<RespuestaListaParametricasDTO>;
}
