// Generated by https://quicktype.io

interface SiatCufd {
	codigo: string;
	codigoControl: string;
	direccion: string;
	fechaVigencia: string;
	mensajesList?: MensajesList[];
	transaccion: boolean;
}

interface MensajesList {
	codigo: number;
	descripcion: string;
}

// Generated by https://quicktype.io

interface SiatCuis {
	codigo: string;
	fechaVigencia: string;
	mensajesList?: MensajesList[];
	transaccion: boolean;
}

// Generated by https://quicktype.io

interface SiatEventoSignificativo {
	codigoEvento: number;
	codigoRecepcionEventoSignificativo: number;
	descripcion: string;
	fechaFin: string;
	fechaInicio: string;
	cufdEvento?: SiatCufd;
}
interface SiatFueraDeLinea {
	codigoEvento: number;
	descripcion: string;
	fechaInicio: string;
	cufdEvento?: SiatCufd;
}
